#!/usr/bin/env python3
"""
plot_telem.py — Telemetry visualiser for GNC docking simulation.

Reads sim/telem.csv (generated by make run) and produces:
  sim/plots/range_vs_time.png/.pdf
  sim/plots/trajectory_lvlh.png/.pdf
  sim/plots/nav_error.png/.pdf
  sim/plots/propulsion.png/.pdf
  sim/plots/dv_budget.png/.pdf

Phase transition times are annotated as vertical lines on all time-series plots.
No interactive windows — uses Agg backend.
"""

import sys
import os

# Force headless backend before any other matplotlib import
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

TELEM_CSV = os.path.join(os.path.dirname(__file__), "telem.csv")
PLOTS_DIR = os.path.join(os.path.dirname(__file__), "plots")

PHASE_COLORS = ["#2196F3", "#4CAF50", "#FF9800", "#F44336"]
PHASE_NAMES  = ["Phase 0: Far-field", "Phase 1: Mid-range",
                "Phase 2: Close", "Phase 3: Terminal"]


def load_telem(path):
    """Load telem.csv; exit with a clear message if missing."""
    if not os.path.exists(path):
        print(f"ERROR: telemetry file not found: {path}", file=sys.stderr)
        print("       Run 'make run' first to generate it.", file=sys.stderr)
        sys.exit(1)

    data = {}
    with open(path, "r") as fh:
        header = fh.readline().strip().split(",")
        cols   = {name: [] for name in header}
        for line in fh:
            vals = line.strip().split(",")
            if len(vals) != len(header):
                continue
            for name, val in zip(header, vals):
                cols[name].append(float(val))

    for key, lst in cols.items():
        data[key] = np.array(lst)

    return data


def detect_phase_transitions(data):
    """
    Detect phase transition times by looking for gaps > 1 in phase proxy.
    We infer phase from range thresholds matching guidance waypoints:
      phase 0: range > 100 m
      phase 1: 20 m < range <= 100 m
      phase 2: 5 m < range <= 20 m
      phase 3: range <= 5 m (terminal)
    Returns list of (time_s, phase_after) for each detected transition.
    """
    rng   = data["range_m"]
    time  = data["time_s"]

    def range_to_phase(r):
        if r > 100.0:
            return 0
        if r > 20.0:
            return 1
        if r > 5.0:
            return 2
        return 3

    phases = np.array([range_to_phase(r) for r in rng])
    transitions = []
    for i in range(1, len(phases)):
        if phases[i] != phases[i - 1]:
            transitions.append((time[i], phases[i]))
    return transitions


def save_fig(fig, name):
    """Save figure as both PNG and PDF."""
    os.makedirs(PLOTS_DIR, exist_ok=True)
    for ext in ("png", "pdf"):
        path = os.path.join(PLOTS_DIR, f"{name}.{ext}")
        fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  saved {name}.png / .pdf")


def add_phase_vlines(ax, transitions, ymin=None, ymax=None):
    """Draw vertical lines at each phase transition."""
    for t_s, phase in transitions:
        color = PHASE_COLORS[min(phase, 3)]
        ax.axvline(x=t_s, color=color, linewidth=0.8, linestyle="--", alpha=0.7)
        if ymin is not None and ymax is not None:
            ax.text(t_s + 5, ymax * 0.95, f"P{phase}",
                    fontsize=7, color=color, va="top")


# ── Plot 1: Range vs Time ─────────────────────────────────────────────────────
def plot_range_vs_time(data, transitions):
    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(data["time_s"], data["range_m"], color="#1565C0", linewidth=1.2)
    ax.axhline(y=0.05, color="red", linewidth=0.8, linestyle=":", label="Dock tol 0.05 m")
    add_phase_vlines(ax, transitions, ymin=0, ymax=data["range_m"].max())
    ax.set_xlabel("Mission time (s)")
    ax.set_ylabel("Range to docking port (m)")
    ax.set_title("Range vs Time")
    ax.set_yscale("log")
    ax.legend(fontsize=8)
    ax.grid(True, which="both", alpha=0.3)
    save_fig(fig, "range_vs_time")


# ── Plot 2: Trajectory in LVLH ────────────────────────────────────────────────
def plot_trajectory_lvlh(data):
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # x-y (radial vs along-track)
    ax = axes[0]
    sc = ax.scatter(data["true_y"], data["true_x"],
                    c=data["time_s"], cmap="viridis",
                    s=1, rasterized=True)
    ax.scatter([0], [0], c="red", s=80, zorder=5, label="Docking port")
    ax.set_xlabel("Along-track y (m)")
    ax.set_ylabel("Radial x (m)")
    ax.set_title("Trajectory: Radial vs Along-track")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)
    fig.colorbar(sc, ax=ax, label="Time (s)")

    # y-z (along-track vs cross-track)
    ax = axes[1]
    sc = ax.scatter(data["true_y"], data["true_z"],
                    c=data["time_s"], cmap="viridis",
                    s=1, rasterized=True)
    ax.scatter([0], [0], c="red", s=80, zorder=5, label="Docking port")
    ax.set_xlabel("Along-track y (m)")
    ax.set_ylabel("Cross-track z (m)")
    ax.set_title("Trajectory: Along-track vs Cross-track")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)
    fig.colorbar(sc, ax=ax, label="Time (s)")

    fig.tight_layout()
    save_fig(fig, "trajectory_lvlh")


# ── Plot 3: Navigation error (true - estimated) per axis ─────────────────────
def plot_nav_error(data, transitions):
    err_x = data["true_x"] - data["est_x"]
    err_y = data["true_y"] - data["est_y"]
    err_z = data["true_z"] - data["est_z"]

    fig, axes = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
    labels = ["Radial x error (m)", "Along-track y error (m)", "Cross-track z error (m)"]
    errs   = [err_x, err_y, err_z]
    colors = ["#1565C0", "#2E7D32", "#6A1B9A"]

    for ax, lbl, err, col in zip(axes, labels, errs, colors):
        ax.plot(data["time_s"], err, color=col, linewidth=0.8)
        ax.axhline(0, color="black", linewidth=0.5)
        add_phase_vlines(ax, transitions,
                         ymin=err.min(), ymax=err.max())
        ax.set_ylabel(lbl, fontsize=8)
        ax.grid(True, alpha=0.3)

    axes[-1].set_xlabel("Mission time (s)")
    axes[0].set_title("Navigation Filter Error (true − estimated)")
    fig.tight_layout()
    save_fig(fig, "nav_error")


# ── Plot 4: Propulsion — per-axis thrust commands ─────────────────────────────
def plot_propulsion(data, transitions):
    fig, axes = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
    labels = ["F_x (N)", "F_y (N)", "F_z (N)"]
    keys   = ["cmd_fx", "cmd_fy", "cmd_fz"]
    colors = ["#1565C0", "#2E7D32", "#6A1B9A"]

    for ax, lbl, key, col in zip(axes, labels, keys, colors):
        ax.plot(data["time_s"], data[key], color=col, linewidth=0.7)
        ax.axhline(0, color="black", linewidth=0.4)
        add_phase_vlines(ax, transitions,
                         ymin=data[key].min(), ymax=data[key].max())
        ax.set_ylabel(lbl, fontsize=8)
        ax.grid(True, alpha=0.3)

    axes[-1].set_xlabel("Mission time (s)")
    axes[0].set_title("Thruster Command vs Time")
    fig.tight_layout()
    save_fig(fig, "propulsion")


# ── Plot 5: Cumulative ΔV budget ──────────────────────────────────────────────
def plot_dv_budget(data, transitions):
    cum_dv = np.cumsum(data["dv_step"])

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(data["time_s"], cum_dv, color="#BF360C", linewidth=1.2)
    add_phase_vlines(ax, transitions, ymin=0, ymax=cum_dv.max())
    ax.set_xlabel("Mission time (s)")
    ax.set_ylabel("Cumulative ΔV (m/s)")
    ax.set_title("ΔV Budget vs Time")
    ax.grid(True, alpha=0.3)

    # Legend for phase lines
    handles = [mpatches.Patch(color=PHASE_COLORS[i], label=PHASE_NAMES[i])
               for i in range(4)]
    ax.legend(handles=handles, fontsize=7, loc="lower right")
    save_fig(fig, "dv_budget")


# ── Plot 6: FDIR fault timeline ───────────────────────────────────────────────
FAULT_LABELS = {0: "NONE", 1: "THR_STUCK_CLOSED", 2: "THR_STUCK_OPEN",
                3: "SENSOR_DROPOUT", 4: "NAV_DIVERGE", 5: "ATT_UNSTABLE"}
MODE_LABELS  = {0: "NOMINAL", 1: "HOLD", 2: "ABORT_RETREAT",
                3: "ABORT_SAFE", 4: "DOCKED", 5: "FAILED"}


def plot_fdir_timeline(data, transitions):
    """Show fault_code and mission_mode vs time.

    In a nominal run both stay at 0 (NONE / NOMINAL) — the flat line
    confirms FDIR is running and no spurious faults were raised.
    """
    if "fault_code" not in data or "mission_mode" not in data:
        print("  skipping FDIR plot (columns not present in telem.csv)")
        return

    fig, axes = plt.subplots(2, 1, figsize=(10, 5), sharex=True)

    ax0 = axes[0]
    ax0.step(data["time_s"], data["fault_code"], where="post",
             color="#C62828", linewidth=1.2)
    ax0.set_ylabel("Fault code")
    ax0.set_yticks(list(FAULT_LABELS.keys()))
    ax0.set_yticklabels([FAULT_LABELS[k] for k in FAULT_LABELS], fontsize=7)
    ax0.set_ylim(-0.2, 5.5)
    ax0.grid(True, alpha=0.3)
    add_phase_vlines(ax0, transitions)
    ax0.set_title("FDIR Fault Code and Mission Mode vs Time")

    ax1 = axes[1]
    ax1.step(data["time_s"], data["mission_mode"], where="post",
             color="#1565C0", linewidth=1.2)
    ax1.set_ylabel("Mission mode")
    ax1.set_yticks(list(MODE_LABELS.keys()))
    ax1.set_yticklabels([MODE_LABELS[k] for k in MODE_LABELS], fontsize=7)
    ax1.set_ylim(-0.2, 5.5)
    ax1.set_xlabel("Mission time (s)")
    ax1.grid(True, alpha=0.3)
    add_phase_vlines(ax1, transitions)

    fig.tight_layout()
    save_fig(fig, "fdir_timeline")


# ── Plot 7: Perturbation effect (Phase 7 gate) ────────────────────────────────
def plot_perturbation_effect(data, transitions):
    """Navigation error (true - estimated) under J2 + drag perturbations.
    Phase 7 verification gate: shows nonzero nav error caused by unmodelled
    perturbations (J2 oblateness + atmospheric drag) acting on the true
    dynamics while the onboard GNC model uses plain CW.
    """
    err_x = data["true_x"] - data["est_x"]
    err_y = data["true_y"] - data["est_y"]
    err_z = data["true_z"] - data["est_z"]

    fig, axes = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
    labels = ["Δx = true − est  (m)", "Δy = true − est  (m)", "Δz = true − est  (m)"]
    errs   = [err_x, err_y, err_z]
    colors = ["#1565C0", "#2E7D32", "#6A1B9A"]

    for ax, lbl, err, col in zip(axes, labels, errs, colors):
        ax.plot(data["time_s"], err, color=col, linewidth=0.8)
        ax.axhline(0, color="black", linewidth=0.5)
        add_phase_vlines(ax, transitions,
                         ymin=err.min(), ymax=err.max())
        ax.set_ylabel(lbl, fontsize=8)
        ax.grid(True, alpha=0.3)

    axes[-1].set_xlabel("Mission time (s)")
    axes[0].set_title("Navigation Error (True - Estimated) under J2 + Drag")
    fig.tight_layout()
    save_fig(fig, "perturbation_effect")


def main():
    print(f"Loading telemetry from {TELEM_CSV} ...")
    data = load_telem(TELEM_CSV)
    n = len(data["time_s"])
    print(f"  {n} records loaded, t_max={data['time_s'][-1]:.1f} s")

    transitions = detect_phase_transitions(data)
    print(f"  Phase transitions detected at: "
          + ", ".join(f"{t:.0f}s→P{p}" for t, p in transitions))

    print("Generating plots ...")
    plot_range_vs_time(data, transitions)
    plot_trajectory_lvlh(data)
    plot_nav_error(data, transitions)
    plot_perturbation_effect(data, transitions)
    plot_propulsion(data, transitions)
    plot_dv_budget(data, transitions)
    plot_fdir_timeline(data, transitions)

    print(f"All plots saved to {PLOTS_DIR}/")


if __name__ == "__main__":
    main()
