#!/usr/bin/env python3
"""
plot_mc.py — Monte Carlo results visualiser.

Reads sim/mc_results.csv (generated by make mc) and produces:
  sim/plots/mc_scatter.png/.pdf    — final pos error vs total DV
  sim/plots/mc_hist_steps.png/.pdf — histogram of steps to docking
  sim/plots/mc_dv_boxplot.png/.pdf — box plot of total DV across seeds

No interactive windows — uses Agg backend.
"""

import sys
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

MC_CSV   = os.path.join(os.path.dirname(__file__), "mc_results.csv")
PLOTS_DIR = os.path.join(os.path.dirname(__file__), "plots")


def load_mc(path):
    if not os.path.exists(path):
        print(f"ERROR: MC results file not found: {path}", file=sys.stderr)
        print("       Run 'make mc N=100' first.", file=sys.stderr)
        sys.exit(1)

    data = {}
    with open(path, "r") as fh:
        header = fh.readline().strip().split(",")
        cols   = {name: [] for name in header}
        for line in fh:
            vals = line.strip().split(",")
            if len(vals) != len(header):
                continue
            for name, val in zip(header, vals):
                cols[name].append(float(val))

    for key, lst in cols.items():
        data[key] = np.array(lst)

    return data


def save_fig(fig, name):
    os.makedirs(PLOTS_DIR, exist_ok=True)
    for ext in ("png", "pdf"):
        path = os.path.join(PLOTS_DIR, f"{name}.{ext}")
        fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  saved {name}.png / .pdf")


def plot_scatter(data):
    """Scatter: final pos error vs total DV, colour = docked/failed."""
    docked  = data["docked"].astype(bool)
    failed  = ~docked

    fig, ax = plt.subplots(figsize=(8, 5))

    if docked.any():
        ax.scatter(data["total_dv_mps"][docked],
                   data["final_pos_err_m"][docked],
                   c="#2196F3", s=20, alpha=0.7, label="Docked")
    if failed.any():
        ax.scatter(data["total_dv_mps"][failed],
                   data["final_pos_err_m"][failed],
                   c="#F44336", s=30, marker="x", alpha=0.9, label="Failed")

    ax.axhline(y=0.05, color="red", linewidth=0.8, linestyle=":",
               label="Dock pos tol 0.05 m")
    ax.set_xlabel("Total ΔV (m/s)")
    ax.set_ylabel("Final position error (m)")
    ax.set_title(f"Monte Carlo: Final Error vs ΔV  (N={len(data['run']):.0f})")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)
    save_fig(fig, "mc_scatter")


def plot_hist_steps(data):
    """Histogram: steps to docking (only docked runs)."""
    docked = data["docked"].astype(bool)
    steps  = data["steps"][docked]

    if len(steps) == 0:
        print("  WARNING: no docked runs — skipping step histogram")
        return

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.hist(steps, bins=30, color="#4CAF50", edgecolor="white", alpha=0.8)
    ax.axvline(x=steps.mean(), color="#1B5E20", linewidth=1.2,
               linestyle="--", label=f"Mean = {steps.mean():.0f} steps")
    ax.set_xlabel("Steps to docking")
    ax.set_ylabel("Count")
    ax.set_title("Histogram: Steps to Docking")
    ax.legend(fontsize=8)
    ax.grid(True, axis="y", alpha=0.3)
    save_fig(fig, "mc_hist_steps")


def plot_dv_boxplot(data):
    """Box plot: total DV split by docked / failed."""
    docked = data["docked"].astype(bool)
    failed = ~docked

    groups = []
    labels = []
    if docked.any():
        groups.append(data["total_dv_mps"][docked])
        labels.append(f"Docked (n={docked.sum()})")
    if failed.any():
        groups.append(data["total_dv_mps"][failed])
        labels.append(f"Failed (n={failed.sum()})")

    if not groups:
        print("  WARNING: no data for boxplot")
        return

    fig, ax = plt.subplots(figsize=(6, 5))
    bp = ax.boxplot(groups, patch_artist=True, notch=False)
    colors = ["#2196F3", "#F44336"]
    for patch, color in zip(bp["boxes"], colors[:len(groups)]):
        patch.set_facecolor(color)
        patch.set_alpha(0.6)

    ax.set_xticklabels(labels, fontsize=9)
    ax.set_ylabel("Total ΔV (m/s)")
    ax.set_title("ΔV Distribution: Docked vs Failed")
    ax.grid(True, axis="y", alpha=0.3)
    save_fig(fig, "mc_dv_boxplot")


def main():
    print(f"Loading MC results from {MC_CSV} ...")
    data = load_mc(MC_CSV)
    n      = len(data["run"])
    docked = int(data["docked"].sum())
    p_dock = docked / n if n > 0 else 0.0
    print(f"  {n} runs loaded  |  docked={docked}/{n}  P={p_dock:.3f}")

    print("Generating plots ...")
    plot_scatter(data)
    plot_hist_steps(data)
    plot_dv_boxplot(data)

    print(f"All MC plots saved to {PLOTS_DIR}/")

    if p_dock < 0.95:
        print(f"FAIL: P(dock)={p_dock:.3f} < 0.95", file=sys.stderr)
        sys.exit(1)
    else:
        print(f"PASS: P(dock)={p_dock:.3f} >= 0.95")


if __name__ == "__main__":
    main()
